// <auto-generated />
using Car_Dealership.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_Dealership.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908103711_RemoveFeatures")]
    partial class RemoveFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_Dealership.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 6,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Porsche"
                        });
                });

            modelBuilder.Entity("Car_Dealership.Models.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FirstPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShowcase")
                        .HasColumnType("bit");

                    b.Property<int>("TransmissionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CarModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Car_Dealership.Models.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CarId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("Car_Dealership.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "RAV4"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "Camry"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Name = "Yaris"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Name = "Hilux"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            Name = "Passat"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            Name = "Polo"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            Name = "Tiguan"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            Name = "T-Roc"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            Name = "Tucson"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            Name = "i20"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            Name = "Elantra"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            Name = "Santa Fe"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            Name = "Bayon"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 4,
                            Name = "Focus"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 4,
                            Name = "Fiesta"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 4,
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 4,
                            Name = "Kuga"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 4,
                            Name = "Mustang"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 5,
                            Name = "Civic"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 5,
                            Name = "City"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            Name = "CR-V"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 5,
                            Name = "HR-V"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 5,
                            Name = "Accord"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 6,
                            Name = "3 Serisi"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 6,
                            Name = "5 Serisi"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 6,
                            Name = "1 Serisi"
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 6,
                            Name = "X1"
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 6,
                            Name = "X5"
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 7,
                            Name = "G-Serisi (G 63 AMG)"
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 7,
                            Name = "E-Serisi"
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 7,
                            Name = "C-Serisi"
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 7,
                            Name = "S-Serisi"
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 7,
                            Name = "GLC"
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 8,
                            Name = "A3"
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 8,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 8,
                            Name = "A6"
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 8,
                            Name = "Q3"
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 8,
                            Name = "Q5"
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 9,
                            Name = "Qashqai"
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 9,
                            Name = "Juke"
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 9,
                            Name = "X-Trail"
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 9,
                            Name = "Micra"
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 9,
                            Name = "Leaf"
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 10,
                            Name = "Macan"
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 10,
                            Name = "Cayenne"
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 10,
                            Name = "Panamera"
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 10,
                            Name = "Taycan"
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 10,
                            Name = "911"
                        });
                });

            modelBuilder.Entity("Car_Dealership.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Password = "hilal123",
                            Role = "Admin",
                            UserName = "Hilal Temel"
                        },
                        new
                        {
                            Id = 2L,
                            Password = "ahmet456",
                            Role = "Customer",
                            UserName = "Ahmet Yılmaz"
                        },
                        new
                        {
                            Id = 3L,
                            Password = "ayse789",
                            Role = "Customer",
                            UserName = "Ayşe Demir"
                        },
                        new
                        {
                            Id = 4L,
                            Password = "mehmet321",
                            Role = "Customer",
                            UserName = "Mehmet Kaya"
                        },
                        new
                        {
                            Id = 5L,
                            Password = "zeynep654",
                            Role = "Customer",
                            UserName = "Zeynep Çelik"
                        },
                        new
                        {
                            Id = 6L,
                            Password = "can987",
                            Role = "Customer",
                            UserName = "Can Arslan"
                        },
                        new
                        {
                            Id = 7L,
                            Password = "elif147",
                            Role = "Customer",
                            UserName = "Elif Şahin"
                        },
                        new
                        {
                            Id = 8L,
                            Password = "burak258",
                            Role = "Customer",
                            UserName = "Burak Koç"
                        },
                        new
                        {
                            Id = 9L,
                            Password = "deniz369",
                            Role = "Customer",
                            UserName = "Deniz Aydın"
                        },
                        new
                        {
                            Id = 10L,
                            Password = "cemre159",
                            Role = "Customer",
                            UserName = "Cemre Yıldız"
                        });
                });

            modelBuilder.Entity("Car_Dealership.Models.Car", b =>
                {
                    b.HasOne("Car_Dealership.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car_Dealership.Models.CarModel", "CarModel")
                        .WithMany("Cars")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("Car_Dealership.Models.CarImage", b =>
                {
                    b.HasOne("Car_Dealership.Models.Car", "Car")
                        .WithMany("Images")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Car_Dealership.Models.CarModel", b =>
                {
                    b.HasOne("Car_Dealership.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Car_Dealership.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Car_Dealership.Models.Car", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Car_Dealership.Models.CarModel", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
