// <auto-generated />
using Car_Dealership.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_Dealership.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260817120445_SeedInitialUsers")]
    partial class SeedInitialUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_Dealership.Models.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Car_Dealership.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Password = "hilal123",
                            Role = "Admin",
                            UserName = "Hilal Temel"
                        },
                        new
                        {
                            Id = 2L,
                            Password = "ahmet456",
                            Role = "Customer",
                            UserName = "Ahmet Yılmaz"
                        },
                        new
                        {
                            Id = 3L,
                            Password = "ayse789",
                            Role = "Customer",
                            UserName = "Ayşe Demir"
                        },
                        new
                        {
                            Id = 4L,
                            Password = "mehmet321",
                            Role = "Customer",
                            UserName = "Mehmet Kaya"
                        },
                        new
                        {
                            Id = 5L,
                            Password = "zeynep654",
                            Role = "Customer",
                            UserName = "Zeynep Çelik"
                        },
                        new
                        {
                            Id = 6L,
                            Password = "can987",
                            Role = "Customer",
                            UserName = "Can Arslan"
                        },
                        new
                        {
                            Id = 7L,
                            Password = "elif147",
                            Role = "Customer",
                            UserName = "Elif Şahin"
                        },
                        new
                        {
                            Id = 8L,
                            Password = "burak258",
                            Role = "Customer",
                            UserName = "Burak Koç"
                        },
                        new
                        {
                            Id = 9L,
                            Password = "deniz369",
                            Role = "Customer",
                            UserName = "Deniz Aydın"
                        },
                        new
                        {
                            Id = 10L,
                            Password = "cemre159",
                            Role = "Customer",
                            UserName = "Cemre Yıldız"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
